name = "dmlg_319520"
version = "0.1.0"
defaultTargets = ["GenLimit"]
moreLeanArgs = ["-j", "4"]

[leanOptions]
warn.sorry = true
warningAsError = true

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "905b95818eb32af7874a58b427f50c1711a5e96c"

[[lean_lib]]
name = "GenLimit"
